<start> ::= <block> <section> <section> <section>
<section> ::= <separator> <block> | <separator>
<block> ::=  <action> <block>?
<conditional_statement> ::= <condition> <conditional_action>
<conditional_action> ::= left_arrow | right_arrow | down_arrow | program1 | program2 | program3 | program4
<action> ::= <do_sth> down_arrow <move>? down_arrow <do_sth>?| <do_sth> down_arrow <move>? <conditional_down> <move>? <conditional_move>? down_arrow <do_sth>?
<do_sth> ::= (<move> | program1|program2|program3|program4)*
<move> ::= left_arrow | right_arrow | <conditional_move>
<conditional_move> ::= <condition> <cond_move>
<cond_move> ::= left_arrow | right_arrow
<condition> ::= all | empty | color1 | color2 | color3 | color4
<conditional_down> ::= <condition> down_arrow
<separator> ::= separator

