<start> ::= <block> <section> <section> <section>
<section> ::= <separator> <block> | <separator>
<block> ::= <block> <block> | <action> | <conditional_statement>
<conditional_statement> ::= <condition> <conditional_action>
<conditional_action> ::= left_arrow | right_arrow | down_arrow | program1 | program2 | program3 | program4
<action> ::= left_arrow | right_arrow | down_arrow | program1 | program2 | program3 | program4
<condition> ::= all | empty | color1 | color2 | color3 | color4
<separator> ::= separator

